version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: vac
      POSTGRES_PASSWORD: M@linin!!!
      POSTGRES_DB: DBbot
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_NAME: DBbot
  #     DB_USER: vac
  #     DB_PASSWORD: M@linin!!!
